name: C/C++ CI

on:
  push:
    branches: [ "branchMake" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: |
        make
    - name: Link
      run: |
        make main
