name: C/C++ Autotools CI

on:
  push:
    branches: [ "branchAutomake" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Autoreconf
      run: |
        autoreconf -i
    - name: Configure
      run: |
        ./configure
    - name: Make
      run: |
        make dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tarball
        path: '*.tar.gz'

